export const playlist = [
    "/assets/music/AgusAlvarez & Luke Bergs - With You (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Luke Bergs - With You (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Markvard - Beautiful Liar (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Sunova - Journey (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Sunova - Move (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Waesto - Hold You (freetouse.com).mp3",
  "/assets/music/AgusAlvarez & Waesto - Hope (freetouse.com).mp3",
  "/assets/music/AgusAlvarez - Sunrise (freetouse.com).mp3",
  "/assets/music/ASHUTOSH - Cuba (freetouse.com).mp3",
  "/assets/music/Aylex - Fashion Queen (freetouse.com).mp3",
  "/assets/music/Aylex - Freshness (freetouse.com).mp3",
  "/assets/music/Aylex - Let's Party (freetouse.com).mp3",
  "/assets/music/Aylex - Live It (freetouse.com).mp3",
  "/assets/music/Aylex - Room Tour (freetouse.com).mp3",
  "/assets/music/Aylex - Sunny Day (freetouse.com).mp3",
  "/assets/music/Aylex - These Days (freetouse.com).mp3",
  "/assets/music/Burgundy - Chances (freetouse.com).mp3",
  "/assets/music/Burgundy - Dreams of Tomorrow (freetouse.com).mp3",
  "/assets/music/Burgundy - Flicker (freetouse.com).mp3",
  "/assets/music/Burgundy - Get Yours, Get Out (freetouse.com).mp3",
  "/assets/music/Burgundy - Ignition (freetouse.com).mp3",
  "/assets/music/Burgundy - Mirrorball (freetouse.com).mp3",
  "/assets/music/Burgundy - Supersonic (freetouse.com).mp3",
  "/assets/music/Burgundy - Tell Me (freetouse.com).mp3",
  "/assets/music/Burgundy - Triumph (freetouse.com).mp3",
  "/assets/music/HiLau & tubebackr - Guava (freetouse.com).mp3",
  "/assets/music/Luke Bergs & Lichu - Exotic (freetouse.com).mp3",
  "/assets/music/Luke Bergs & Markvard - Our Way (freetouse.com).mp3",
  "/assets/music/Luke Bergs & Waesto - Holiday (freetouse.com).mp3",
  "/assets/music/Luke Bergs - Call For Love (freetouse.com).mp3",
  "/assets/music/Luke Bergs - Sunlight (freetouse.com).mp3",
  "/assets/music/Luke Bergs - Take It Easy (freetouse.com).mp3",
  "/assets/music/Luke_Bergs&Waesto.mp3",
  "/assets/music/Moavii - Avenue (freetouse.com).mp3",
  "/assets/music/Moavii - Bon Aleè (freetouse.com).mp3",
  "/assets/music/Moavii - Canariea (freetouse.com).mp3",
  "/assets/music/Moavii - Feeling Good (freetouse.com).mp3",
  "/assets/music/Moavii - Greece (freetouse.com).mp3",
  "/assets/music/Moavii - Just A Minute (freetouse.com).mp3",
  "/assets/music/Moavii - Lets Go (freetouse.com).mp3",
  "/assets/music/Moavii - Oveza (freetouse.com).mp3",
  "/assets/music/Moavii - Paradise Palms (freetouse.com).mp3",
  "/assets/music/Moavii - Thats Right (freetouse.com).mp3",
  "/assets/music/N3X - Anymore (freetouse.com).mp3",
  "/assets/music/N3X - Anything (freetouse.com).mp3",
  "/assets/music/N3X - Feel You (freetouse.com).mp3",
  "/assets/music/N3X - On My Own (freetouse.com).mp3",
  "/assets/music/N3X - Tell Me (freetouse.com).mp3",
  "/assets/music/N3X - This Life (freetouse.com).mp3",
  "/assets/music/N3X - You & I (freetouse.com).mp3",
  "/assets/music/Ocean Bloom - Latin Sunset (freetouse.com).mp3",
  "/assets/music/Popsicles - Without You (freetouse.com).mp3",
  "/assets/music/shandr - Fever (freetouse.com).mp3",
  "/assets/music/Sunova - Mood (freetouse.com).mp3",
  "/assets/music/Sunova - Palms (freetouse.com).mp3",
  "/assets/music/Sunova - Rainbow (freetouse.com).mp3",
  "/assets/music/Waesto - Beach Life (freetouse.com).mp3",
  "/assets/music/Waesto - Found You (freetouse.com).mp3",
  "/assets/music/Waesto - Funky (freetouse.com) (1).mp3",
  "/assets/music/Waesto - Last Chance (freetouse.com).mp3",
  "/assets/music/Waesto - Ocean Vibes (freetouse.com).mp3",
  "/assets/music/Waesto - Sunset (freetouse.com).mp3",
  "/assets/music/Walen - Bali (freetouse.com).mp3",
  "/assets/music/Walen - Beach Party (freetouse.com).mp3",
  "/assets/music/Walen - Desert Caravan (freetouse.com).mp3",
  "/assets/music/Walen - Monday (freetouse.com).mp3",
  "/assets/music/Walen - Pineapple (freetouse.com).mp3",
];
// const playlist =[
//     "https://zaiocontent.S3.eu-west-2.amazonaws.com/sound-effects/tick.mp3",
//     "https://zaiocontent.S3.eu-west-2.amazonaws.com/sound-effects/click.wav"
// ]

export default playlist